[project]
name = "molecular_dynamics"
version = "0.1.0"
description = "A package that allows you to analyze trajectories from molecular dynamics (MD) simulations."
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "jupyter (<1.2)",
    "matplotlib (<3.11)",
    "loguru (<0.8)",
    "numba (<0.66)",
    "numpy (<2.5)",
    "pandas (<3.1)",
    "pylint-af (<1.1)",
    "scikit-learn (<1.9)",
]

[dependency-groups]
dev = [
    "pytest (<10.0)",
    "pytest-cov (<8.0)",
    "pytest-django (<5.0)",
    "pytest-mock (<4.0)",
    "ruff (<1.0)",
    "ty (<1.0)",
    "wemake-python-styleguide (<2.0)",
]
